# synch changes to master here back to the bit bucket copy.

name: Synch BitBucket

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:

jobs:
  testenv:
    name: Test Env vars
    runs-on: ubuntu-latest
    steps:
      - name: Print env vars 
        run: echo Hello world $FIRST_NAME $S1 $S2
        env:
          FIRST_NAME: Mona
          S1: ${{ secrets.BITBUCKET_CREDS }}
          S2: ${{ github.repository }}

  syncbb:
    name: Synch from Github to Bitbucket
    runs-on: ubuntu-latest
    steps:
      - name: pull the github repo
        uses: actions/checkout@v2
      
      - name: sync with bitbucket
        env:
          BB_REPO: https://$BITBUCKET_CREDS@bitbucket.org/$REPO.git
          BB_REPO2: https://${{ secrets.BITBUCKET_CREDS }}@bitbucket.org/${{ github.repository }}.git

        run: |
          echo "bb_repo is $BB_REPO2"
          cd $GITHUB_WORKSPACE
          git fetch --prune --unshallow
          git config user.email andrew@groat.nz
          git config user.name "Andrew Watkins"
          git remote add sync https://${{ secrets.BITBUCKET_CREDS }}@bitbucket.org/${{ github.repository }}.git
          # git pull sync master --allow-unrelated-histories
          git push --force --set-upstream -v --all sync
         
     