# synch changes to master here back to the bit bucket copy.

name: Synch BitBucket

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "syncbb"
  syncbb:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Runs a set of commands using the runners shell
    - name: pull the bb rep
      env:
        BITBUCKET_CREDS: ${{ secrets.BITBUCKET_CREDS }}
      run: |
        echo "$BITBUCKET_CREDS"
        ls
        git clone https://"$BITBUCKET_CREDS"@bitbucket.org/groat_nz/enterprise-demo.git $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        ls
        git status
        git remote show origin

    # - name: Updating repo from Github
    #   run: |
    #     echo Updating BitBucket from Github     
    #     cd $GITHUB_WORKSPACE   
    #     git pull sync master  
    #     git push
        
        
