# This action mirrors a github repo into a similar bitbucket one
# requires the bb workspace/repo and the github org/repo to match
# e.g.  groatnz/demo

# Setup
# 1 create git hub repo and add this file to the .github/workflows
# 2 create an empty repo in bit bucket with the same name
# commit a change to the github repo
# it should be reflected into the bb repo. 

name: Synch BitBucket

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:

jobs:

  comparecreds:
    name: Compare Credentials
    runs-on: ubuntu-latest
    steps:
      - name: test
        env:
          BB_CREDS: "groat-nz:Mojo,00jimk-2019-atlassian.com"
          CC_CREDS: ${{ secrets.BITBUCKET_CREDS }}
        run: |
          if [ $BB_CREDS = "$VAR2" ]; then
            echo $BB_CREDS is same as $CC_CREDS
          else
            echo $BB_CREDS is not the same as $CC_CREDS
          fi
         
  syncbb:
    name: Synch from Github to Bitbucket
    runs-on: ubuntu-latest
    steps:
      - name: pull the github repo
        uses: actions/checkout@v2
      - name: sync with bitbucket
        env:
          BB_CREDS: "groat-nz:Mojo,00jimk-2019-atlassian.com"
        run: |
          cd $GITHUB_WORKSPACE
          git fetch --prune --unshallow
          git config user.email andrew@groat.nz
          git config user.name "Andrew Watkins"
          git remote add sync https://$BB_CREDS@bitbucket.org/${{ github.repository }}.git
          # git pull sync master --allow-unrelated-histories
          git push --force --set-upstream -v --all sync
         
     