# synch changes to master here back to the bit bucket copy.

name: Synch BitBucket

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:

env:
  BITBUCKET_CREDS: ${{ secrets.BITBUCKET_CREDS }}
  REPO: ${{ github.repository }}

jobs:
  syncbb:
    name: Synch from Github to Bitbucket
    runs-on: ubuntu-latest
    steps:
      - name: pull the github repo
        uses: actions/checkout@v2
      
      - name: sync with bitbucket
        run: |
          echo "github.repository is $GITHUB_REPO"
          echo "bb_repo is $BB_REPO"
          cd $GITHUB_WORKSPACE
          git fetch --prune --unshallow
          git config user.email andrew@groat.nz
          git config user.name "Andrew Watkins"
          git remote add sync https://$BITBUCKET_CREDS@bitbucket.org/$REPO.git
          git remote -v
          # git pull sync master --allow-unrelated-histories
          git push --force --set-upstream -v --all sync
         
     